app_name: Vampire Survivors Companion
app_subtitle: Unofficial Vampire Survivors Helper
app_download: https://apps.apple.com/app/id1608872206
app_github: 
app_id: 1608872206
email: kevin.renella@gmail.com
app_icon: /assets/icon.png
favicon: /assets/icon.png

made_by: Made by [Drusy](https://github.com/drusy)

links:
  - title: Donation
    url: https://paypal.me/kevinrenella
  - title: Exile Companion
    url: https://drusy.github.io/exile-companion
  - title: Clash Mini Companion
    url: https://drusy.github.io/clash-mini-companion

app_description: |
    Unofficial Vampire Survivors companion app. 
    
    ## Features
    
    Start a new run and select your weapons and accessories to see what evolution you can get !
    
    Details of the following content
    - Characters
    - Weapons
    - Evolutions
    - Accessory
    - PowerUp
    - Stages 
    
    ## Disclaimer
    
    This app is not the official Vampire Survivors application and is not related to poncle in any way.

####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

plugins:
  - jekyll-postcss

exclude:
  - Gemfile
  - Gemfile.lock
  - package-lock.json
  - README.md
  - postcss.config.js
  - .gitignore
  - node_modules

markdown: kramdown

collections:
  pages:
    output: true
    permalink: /:path/

defaults:
  - scope:
      path: "assets/screenshots"
    values:
      screenshot: true
